### ISSUE TITLE
Editor: Add suggested course

### ISSUE THREAD

**Issue by wceolin** [zoonk/uneebee#108]
On the lesson step, allow to add a suggested course. It allows to add only courses from the current school for now.
```[tasklist]
### Tasks
- [x] Add schema
- [x] Create suggested course
- [x] Delete suggested course
- [x] List suggested courses
- [x] Search courses by title, slug
- [x] Editor: Button to add suggested course (opens search box)
- [x] Search box: Clicking on the result adds course
- [x] Editor: List suggested courses
- [x] Editor: Remove suggested course
- [x] Adds tests for controller
- [x] Update locale
```
