### ISSUE TITLE
Billing: Require paid plan for child schools if they have more than 5 users

### ISSUE THREAD

**Issue by wceolin** [zoonk/uneebee#11]
```[tasklist]
### Tasks
- [ ] When a payment is made, subscription is renewed for more 30 days.
- [ ] Renewal happens even for free accounts (those with 5 users or less).
- [ ] If the school has more than 5 users and subscription is expired for over 30 days, then cancel subscription.
- [ ] If the school has more than 5 users and subscription expired less than 30 days, then display warning.
- [ ] If the school has more than 5 users but subscription is active, then do nothing.
```

**Comment by wceolin** [comment]
This is going to be handled on #8.
