### ISSUE TITLE
LessonStep: Fill in the blank format

### ISSUE THREAD

**Issue by ceolinwill** [zoonk/uneebee#142]
```[tasklist]
### LessonStep
- [x] Add new kind: `fill_the_blank`
- [x] Create a new changeset for `fill_the_blank` steps
- [x] Content shouldn't be required for `fill_the_blank` kind
- [x] Add new segments field (list)
- [x] `segments` field should be required for `fill_the_blank`
- [x] Migration: Allow `content` to be `null`
```

```[tasklist]
### StepOption
- [x] Create new changeset for `fill_the_blank` steps
- [x] Add `segment` field (`int`)
- [x] Fill the blank changeset: Cast only `segment`, `title`, and `lesson_step_id`
```

```[tasklist]
### Editor: Fill in the blank
- [x] Add the `fill_the_blank` kind
- [x] Automatically add 3 example segments
- [x] Automatically add two options
- [x] One option should be linked to a segment
- [x] Option associated with a segment should use the segment's index
- [x] When making a segment empty, adds an option associated with it
- [x] When adding content to an empty segment, remove its associated
- [x] When deleting an option associated with a segment, also remove the segment
- [x] When deleting a segment, also delete its option if it has one
- [x] When deleting a segment, update option segment index
- [x] List segments
- [x] Empty segments should have a different decorator
- [x] Display a + button to add a new segment
- [x] Allow to edit segments
- [x] Allow to delete segments
- [x] List options for fill in the blank steps
- [x] Edit options for fill in the blank steps (see current segment)
```

```[tasklist]
### Play: Fill in the blank
- [ ] Display segments
- [ ] Display empty spaces for empty segments
- [ ] When an option is clicked it's added to the next empty segment
- [ ] When an option is clicked on a segment, it's removed from that segment
- [ ] Submit: Correct: Must match the correct segments
- [ ] Submit: Error: When at least one segment doesn't match
- [ ] Submit: Error: Feedback: Display both the answer and the correct sentence
- [ ] Submit: Double check user selection
```

```[tasklist]
### Tasks
- [ ] Make sure score is properly calculated for `fill_the_blank` steps
```

```[tasklist]
### Dashboard
- [ ] Properly display user selections for `fill_the_blank` steps
```
