### ISSUE TITLE
Gameplay: Allow to disable sound effects

### ISSUE THREAD

**Issue by wceolin** [zoonk/uneebee#61]
Feedback I got:

> I don't see any way to disable the annoying chime; I appreciate this may be a demo app, but it should show that such a thing is possible

Those sound effects can be quite annoying. We should have a way to disable them. I propose that we actually make them disabled by default. 

```[tasklist]
### Tasks
- [x] Add setting to disable sound effects
- [x] Make sound effects disabled by default
- [x] Only run sound effects when they're enabled.
```
