### ISSUE TITLE
Allow guest users for public orgs

### ISSUE THREAD

**Issue by wceolin** [zoonk/uneebee#66]
```[tasklist]
### Tasks
- [x] Add `guest?` field to `User` schema.
- [x] Add `allow_guest?` field to `School` schema.
- [x] School: Don't allow private schools to allow guest users.
- [x] School setting: If public, then enable `allow_guest?` field.
- [x] Accounts: Add function to create a guest user.
- [x] Plug: If school allows guest users, then create guest user, log in, and show page.
- [x] Plug: If school doesn't allow guest user, then redirect to the login page.
- [x] Doesn't create guest user for dashboard routes
- [x] Keep guest user logged in (remember me checked)
- [x] If the guest user has completed more than one lesson, then display message asking to update its account.
- [x] Don't require password for updating email address when it's a guest account.
- [x] Add explanation to email form for guest account
- [x] Send reset password email when updating email for guest account
- [x] When a guest user updates its email address, then set `guest?` to `false`.
- [x] Plug: If the school doesn't allow guests and the user is a guest, then logout and redirect to the login page.
- [x] Update locale.
```
