### ISSUE TITLE
Dashboard: Allow to delete school

### ISSUE THREAD

**Issue by wceolin** [zoonk/uneebee#90]
```[tasklist]
### Tasks
- [x] Dashboard: Manage school: Add a "delete school" menu
- [x] Dashboard: Delete school: Use the same layout as "delete course"
- [x] Delete school: Success: Redirect to the parent school (@app.custom_domain)
- [x] Don't show the delete menu a school if it doesn't have a parent school (school_id is nil)
- [x] Add delete school button to school view on the dashboard
- [x] Deleting a school should delete all its school users
- [x] Deleting a school should delete all its courses
- [x] Deleting a school should delete all its subscriptions
- [x] Deleting a school should delete all its child schools
```
