### ISSUE TITLE
Settings: Allow to delete user account

### ISSUE THREAD

**Issue by wceolin** [zoonk/uneebee#91]
```[tasklist]
### Tasks
- [ ] Settings: Add a new "Delete" menu
- [ ] Settings: Delete: Use the DeleteItem component
- [ ] Delete: Success: Redirect to the sign up page
```
