### ISSUE TITLE
Guest user: Create setup page

### ISSUE THREAD

**Issue by wceolin** [zoonk/uneebee#96]
```[tasklist]
### Tasks
- [x] Settings: Hide the "email" menu when it's a guest user
- [x] Settings: Hide the "password" menu when it's a guest user
- [x] Settings: Show a setup menu when it's a guest user
- [x] Guest warning bar: Link to the setup page
- [x] Guest setup page: Configure email and password
```
